#!/usr/bin/env python3
"""
Crucible evidence-indexing — generate INDEX.md per evidence directory.

Walks evidence/ and writes one INDEX.md per directory enumerating its artifacts
(filename + size + brief description from filename pattern). README.md files are
preserved (they document purpose; INDEX.md documents contents).

Per PRD §3 ED-3 ED-4: every directory must have INDEX.md; no directory may be
empty at gate-completion time.

Usage:
    python3 build_index.py

Environment:
    EVIDENCE_ROOT — required, absolute path to evidence/

Exit codes:
    0  all directories indexed; none empty
    2  at least one directory is empty (refused — gates must produce content)
"""

import os
import sys
from pathlib import Path


# Filename patterns → one-line descriptions
PATTERN_DESCRIPTIONS = (
    ("vg0-tree.txt",            "VG-0: directory tree snapshot"),
    ("vg0-readme-count.txt",    "VG-0: README count receipt"),
    ("vg0-source-sizes.txt",    "VG-0: PRD + ARCHITECTURE line-count receipt"),
    ("vg0-toolchain.txt",       "VG-0: toolchain version inventory"),
    ("vg0-verdict.md",          "VG-0: gate verdict"),
    ("vg1-source-count.txt",    "VG-1: source file count"),
    ("vg1-url-count.txt",       "VG-1: URL field count in SUMMARY"),
    ("vg1-fact-count.txt",      "VG-1: cited-fact count in SUMMARY"),
    ("vg1-line-floor.txt",      "VG-1: line-floor compliance per source"),
    ("vg1-verdict.md",          "VG-1: gate verdict"),
    ("vg2-manifest.json",       "VG-2: jq-canonicalized plugin.json"),
    ("vg2-tree.txt",            "VG-2: plugin directory layout"),
    ("vg2-validate.txt",        "VG-2: claude plugin validate output"),
    ("vg2-validate-exit.txt",   "VG-2: claude plugin validate exit code"),
    ("vg2-verdict.md",          "VG-2: gate verdict"),
    ("vg3-skills.txt",          "VG-3: per-skill SKILL.md frontmatter inspection"),
    ("vg3-forbidden.txt",       "VG-3: forbidden-pattern grep results (must be empty)"),
    ("vg3-verdict.md",          "VG-3: gate verdict"),
    ("PRD.md",                  "Crucible Product Requirements Document (imported)"),
    ("ARCHITECTURE.md",         "Crucible architecture extracted from PRD §4 (12 Mermaid diagrams)"),
    ("SUMMARY.md",              "Cited-facts summary"),
    ("CANONICAL-SOURCES.md",    "Documentation source URL manifest"),
    ("fetch-log.txt",           "VG-1: per-source curl receipts (byte/line counts)"),
    ("README.md",               "Directory purpose + MSC mapping"),
    ("INDEX.md",                "Artifact enumeration (this file)"),
)


def describe(name: str) -> str:
    for pattern, desc in PATTERN_DESCRIPTIONS:
        if name == pattern or name.endswith(pattern):
            return desc
    if name.startswith("step-"):
        return "Validation step artifact"
    if name.startswith("trial-"):
        return "Robust-trial subdirectory"
    if name.endswith(".jsonl"):
        return "JSONL session/transcript log"
    if name.endswith(".md"):
        return "Markdown document"
    if name.endswith(".json"):
        return "JSON document"
    if name.endswith(".txt"):
        return "Plain text receipt"
    return "Artifact"


def build_index(directory: Path, evidence_root: Path) -> tuple[Path, int]:
    rel = directory.relative_to(evidence_root) if directory != evidence_root else Path(".")
    out = directory / "INDEX.md"

    artifacts = sorted(directory.iterdir(), key=lambda p: p.name)
    lines = [f"# {rel}/", ""]
    lines.append(f"Auto-generated by `evidence-indexing` skill (build_index.py).")
    lines.append("")

    if not artifacts:
        lines.append("**EMPTY — no artifacts present.** PRD §3 ED-4 forbids empty directories at gate-completion time.")
        out.write_text("\n".join(lines) + "\n")
        return (out, 0)

    lines.append("| Artifact | Size | Description |")
    lines.append("|----------|------|-------------|")
    count = 0
    for a in artifacts:
        if a.name == "INDEX.md":
            continue
        size = a.stat().st_size
        if a.is_dir():
            size_str = f"({len(list(a.iterdir()))} entries)"
        else:
            size_str = f"{size:,} bytes"
        desc = describe(a.name)
        lines.append(f"| `{a.name}` | {size_str} | {desc} |")
        count += 1

    out.write_text("\n".join(lines) + "\n")
    return (out, count)


def main() -> int:
    evidence_root_env = os.environ.get("EVIDENCE_ROOT")
    if not evidence_root_env:
        print("REFUSED: EVIDENCE_ROOT env var not set", file=sys.stderr)
        return 2
    evidence_root = Path(evidence_root_env)

    empty_dirs = []
    indexed = 0
    for d in [evidence_root] + sorted(p for p in evidence_root.rglob("*") if p.is_dir()):
        out, count = build_index(d, evidence_root)
        indexed += 1
        # Only flag as empty if it contains zero non-INDEX/README files AND no subdirs
        non_meta = [a for a in d.iterdir() if a.name not in ("INDEX.md", "README.md")]
        if not non_meta:
            empty_dirs.append(str(d.relative_to(evidence_root)))

    print(f"Indexed {indexed} directories.")
    if empty_dirs:
        print(f"WARNING: {len(empty_dirs)} directories are empty (no non-meta artifacts):")
        for d in empty_dirs:
            print(f"  - {d}")
        # Empty is allowed PRE-gate but forbidden POST-gate; this script doesn't
        # know which gate is current, so warn-only here. completion-gate (gate.py)
        # is the authoritative empty-check at MSC-16.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
